### ISSUE TITLE
Can't make Multipube

### ISSUE THREAD

**Issue by liu9920ai** [lukejdav/AllTheTiers#5]
Can't make Multipube because the red datacube is locked, can someone tell me how to unlock the red datacube?
<img width="1277" alt="something locked" src="https://github.com/lukejdav/AllTheTiers/assets/76763099/835a9538-fc6e-4533-aedb-9c85ed7517f4">
red datacube:
<img width="1280" alt="red datacube" src="https://github.com/lukejdav/AllTheTiers/assets/76763099/40fc7718-7d68-40b8-b44b-708da254bd65">

**Comment by lukejdav** [comment]
I believe this may be an issue with a recent update of the main game.

It used to be that aliens appeared in the blight and when killing them they would drop a red datacube and that unlocks the relevant research tree.
Try and find some aliens in the blight and kill them.

If you cannot find any, I will update the multicube recipe to no longer include the red datacube.

**Comment by liu9920ai** [comment]
> I believe this may be an issue with a recent update of the main game.
> 
> It used to be that aliens appeared in the blight and when killing them they would drop a red datacube and that unlocks the relevant research tree. Try and find some aliens in the blight and kill them.
> 
> If you cannot find any, I will update the multicube recipe to no longer include the red datacube.

I've killed and hacked many aliens, but nothing has fallen, just a rapidly vanishing alien device
An alien device that quickly disappears:
<img width="1258" alt=" 2024-03-07 135537" src="https://github.com/lukejdav/AllTheTiers/assets/76763099/bf4d361e-f5c3-43a1-8a59-b373d6e6e596">
Hacked aliens:
<img width="1280" alt=" 2024-03-07 135630" src="https://github.com/lukejdav/AllTheTiers/assets/76763099/727a2296-30a7-4129-9cd0-885ea1d1faa1">
It would be great if you could update the recipe, thank you very much

**Comment by liu9920ai** [comment]
> I believe this may be an issue with a recent update of the main game.
> 
> It used to be that aliens appeared in the blight and when killing them they would drop a red datacube and that unlocks the relevant research tree. Try and find some aliens in the blight and kill them.
> 
> If you cannot find any, I will update the multicube recipe to no longer include the red datacube.

I've been experimenting for a long time and found out that the new version of the way to unlock alien technology is to explore the alien ruins in the new version, you can get alien artifacts, and unlock obsidian blocks that can unlock the first stage of alien technology.
Alien ruins that unlock obsidian blocks:
<img width="1280" alt="image" src="https://github.com/lukejdav/AllTheTiers/assets/76763099/aa50a6af-cfcb-4f20-84b5-88f3bdd03b23">
Alien technology:
<img width="1280" alt="屏幕截图 2024-03-08 163619" src="https://github.com/lukejdav/AllTheTiers/assets/76763099/959d072e-ce10-412c-b4c1-a63bb146e49b">
Thank you for your help.

**Comment by lukejdav** [comment]
I'm glad you found out how to unlock them and that everything is working now.

**Comment by liu9920ai** [comment]
> I'm glad you found out how to unlock them and that everything is working now.

This is the new alien tech tree, if you are interested, you can open the latest experimental version of the game on Steam to experience it.
![image](https://github.com/lukejdav/AllTheTiers/assets/76763099/e47f2b48-268b-4980-ae34-9512daed0524)
