### ISSUE TITLE
Recipe loop

### ISSUE THREAD

**Issue by mp5093** [lukejdav/AllTheTiers#6]
Multicube recipe is looped due to game updating.  Multicube requires alien datacubes, which require dense anomaly clusters, which require anomaly particles, which require multicubes.

**Comment by lukejdav** [comment]
I am aware of this bug.
I have been working on updating the mod to be more in line with the base game as well as a lot of overall rebalancing.
Hopefully I can push this code soon and update the mod in the steam workshop.

**Comment by lukejdav** [comment]
I have fixed this and will be updating the steam workshop now.
